### ISSUE TITLE
Launch application. Reward 12 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Titter-WRIO-App#10]
Update the code to launch application. Create static page on github pages with tweet field to check.
More info https://github.com/webRunes/Titter-WRIO-App/issues/1

**Comment by AlexeyAnshakov** [comment]
Please prepare a test page so we can test asap Umair send server update

**Comment by bhushano7** [comment]
Test page for ?

**Comment by AlexeyAnshakov** [comment]
>Create static page on github pages with tweet field to check.

We need an htm with text field, after login (use Login app, add twitter login button) user can send tweet as a pic to his twitter account
