### ISSUE TITLE
Build issue. Reward 5 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Titter-WRIO-App#16]
After changing
>https://github.com/webRunes/Titter-WRIO-App/blob/master/widget/titter.htm

no update on
>http://wrio.s3-website-us-east-1.amazonaws.com/Titter-WRIO-App/widget/titter.htm

though build is passed:
>https://travis-ci.org/webRunes/Titter-WRIO-App

**Comment by umairadeeb** [comment]
Issue has been fixed.
