### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Titter-WRIO-App#192]
Взять копию json-ld с
>webrunes.com

и положить в Titter, чтобы страница открывалась по
>titter.wrioos.com

Страница с полем ввода пусть открывается по запросу
>titter.wrioos.com?create

**Comment by AlexeyAnshakov** [comment]
Перенести в папку hub

**Comment by AlexeyAnshakov** [comment]
Перенести в корень hub, не в src

**Comment by AlexeyAnshakov** [comment]
Поле titter.wrioos.com?create должно отображаться внутри страницы хаба.

**Comment by michbil** [comment]
Can be closed.

**Comment by AlexeyAnshakov** [comment]
It's wrong, not http://wrioos.com/?create but http://titter.wrioos.com?create
