### ISSUE TITLE
Publish the widget. Reward 5 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Titter-WRIO-App#23]
На http://webrunes.com/ есть поле для Titter'а. 
Лежит оно здесь
https://github.com/webRunes/Titter-WRIO-App/blob/master/widget/titter.htm
Нужно перенести функционал на него и удалить titter1.html

**Comment by AlexeyAnshakov** [comment]
Не нужно отображать текст в comments, он там будет появляться из Twitter timeline. После нажатия на Send, твит в виде картинки должен публиковаться в twitter.com/webRunes

**Comment by michbil** [comment]
Почему-то canvas не скрылся, проверю стили. Отсылка работает.
