### ISSUE TITLE
Picture generation. Reward ??? USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Titter-WRIO-App#29]
Привести картинки Titter твитов к виду
>https://pbs.twimg.com/media/B1AuvTyCEAArPd4.png:large

Пример этой картинки можно видеть в 
>https://twitter.com/webRunes

**Comment by michbil** [comment]
Starting to work

**Comment by AlexeyAnshakov** [comment]
Размер и шрифт не совпадают с примером
https://pbs.twimg.com/media/BkUhwV_IQAAykqE.png:large
Добавить внизу твитов
>Posted via Titter - Advanced tweets http://titter.webrunes.com
Сейчас высота твита фиксирована, чего не должно быть - см. приведенный выше пример.

**Comment by AlexeyAnshakov** [comment]
В текстовой части твита должна быть только ссылка страницы с которой уходит твит и сумма донейта. Пока она всегда будет 0. В итоге твит должен получаться вида:
>webrunes.com Donate 0 WRG

и картинкой под текстом
