### ISSUE TITLE
Titter login

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Titter-WRIO-App#330]
В случае отмены логина в титтере происходит редирект на
http://login.wrioos.com/?auth
Должна открываться страница с которой пришел пользователь.

**Comment by michbil** [comment]
Т.е. если авторизация поисходила в попапе, то предыдущая страничка тоже должна отрыться в попапе?

**Comment by AlexeyAnshakov** [comment]
Нет, если пользователь логинился на webrunes.com, то и возвращать на нее.
