### ISSUE TITLE
Enable comments

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/Titter-WRIO-App#77]
[fixed]

Ссылка включения комментариев должна быть видна лишь автору страницы, т.е. сделать проверку на совпадение URL профайла пользователя (см.ссылку My profile в тикете Login на любой странице) с URL в JSON-LD

> "author": "url here",

При создании страницы 

> http://core.wrioos.com/

добавить поле Author где указывать URL взятый из тикета Login. См.  #https://github.com/webRunes/Core-WRIO-App/issues/23

В случае открытия страницы не автором он должен видеть блок "Comments disabled".
Если комментарии активированы, но пользователь не залогинен, то отображать как в прототипе

> blogs-post-enable-comments.htm

прототип был обновлен.

Заменить поле для ввода скрипта для комментирования на кнопку "Add comments". После нажатия на нее вызывать в попапе с iframe (если получится) страницу создания виджета вида

> https://twitter.com/settings/widgets/new/search?query=domain.com%2Fpage.htm

где в query выставляется URL страницы. URL должен браться из ссылки на пользовательский профайл + имя страницы из header (имя под которым будет сохранена страница). Пользователю будет показана инструкция создания виджета и вставки кода (позже добавим). После этого система должна автоматически парсить ID из кода (возможно?) и вставлять в json-ld.

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/Core-WRIO-App/issues/14

**Comment by AlexeyAnshakov** [comment]
См. blogs-post-enable-comments.htm в прототипе.
Три случая:
1. пользователь не залогинен/залогинен, но комментарии отключены автором: 
отображать
```
Comments disabled
Comments haven't been enabled by author
```

кнопку "Enable comments" не отображать
2. не залогинен и комментарии включены автором:
отображать
```
Start to donate and comment!
Please login with Twitter account to be able to comment via tweets and make donations.
Looking forward to hearing from you!
[Join the conversation]
```

3. автор видит свою страницу:
отображать
```
Comments disabled
[Enable comments]
```
в данном случае не отображать текст "Comments haven't been enabled by author".

**Comment by AlexeyAnshakov** [comment]
См. п. 3.

**Comment by michbil** [comment]
Опишите последовательность, как повторить баг

**Comment by AlexeyAnshakov** [comment]
После нажатия [Join the conversation]
https://wr.io/122942999005/
разлогиниться. В FF

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/WRIO-InternetOS/issues/572

Нужно иметь ввиду, что для титтера необходимо добавлять index.html для корректного поиска твитов. Без указания точной страницы поиск будет выдавать твиты для всех страниц лежащих в данной директории. Также нужно поправить титтер, т.к. твиты отправляются с нужным url дишь для
https://webrunes.com/index.html#
но не при открытии
https://webrunes.com

Символ "#" надо убрать из url при открытии. Очевидно, что он добавляется из-за обработки якорей вроде https://webrunes.com/index.html#Team

**Comment by AlexeyAnshakov** [comment]
В случае открытия
https://alternative.webrunes.org
будучи не залогиненным нажать "Join the conversation":
* не появляется титтер таймлайн
* в случае перехода на другой таб и возвращения на данный - неправильная высота у поля ввода твитов

**Comment by AlexeyAnshakov** [comment]
При открытии страницы с #, например
>https://webrunes.com/#Join_us

#text добавляется в комментарий и, соответственно, такой комментарий не отображается на странице.

**Comment by AlexeyAnshakov** [comment]
После включения комментариев нужно обновлять страницу, т.к. иначе все равно видна кнопка "Enable comments" после ее нажатия вместо "Start to donate and comment!" в случае незалогиненного пользователя. После логина таймлайн все равно не появляется, приходится перезагружать страницу снова.

**Comment by AlexeyAnshakov** [comment]
Вернуть текст, что появлялся
>You've donated 10 WRG. Thank you! Comment will appear in a minute
после отсылки комментария

**Comment by AlexeyAnshakov** [comment]
В FF при открытии страницы https://wrioos.com/#How_it_works твит уходит с "#" см. https://twitter.com/webRunes

**Comment by AlexeyAnshakov** [comment]
Если нет текста в поле "Let us know your thoughts! Max 1024 characters", то твит не уходит. Проблему можно решить добавляя пробел в случае отсутствия текста.

**Comment by AlexeyAnshakov** [comment]
на https://titter.wrioos.com/# комментарии уходят без index.html и потому не отображаются. Только когда открыл как https://titter.wrioos.com/index.html#
в комментарий добавился index.html и отобразился

по аналогичной причине работают комментарии для страниц вроде https://wr.io/474365383130/?wr.io=474365383130#

**Comment by AlexeyAnshakov** [comment]
Скрывать поле ввода доната для автора поста.

**Comment by AlexeyAnshakov** [comment]
```
https://wr.io/474365383130/Mind_Field_(Ep_8)
с нее отправляются твиты с одним лишь index.html 
```

нашел проблему. если отправлять с
https://wr.io/474365383130/Mind_Field_(Ep_8)/#Do_You_Know_Yourself?_-_Mind_Field_(Ep_8)
или
https://wr.io/474365383130/Mind_Field_(Ep_8)/#Special_thanks_to_our_guests:

т.е. нажав на пункты в меню. в первом случае явно проблема из-за "?", во втором ":"
